<!--
IF YOUR WORKSHOP DOES NOT INCLUDE COMPUTE:
- REMOVE "AND COMPUTE SETUP" FROM THE TOP-LEVEL HEADER
- DELETE THE LAST SECTION (COMPUTE SETUP)

IF YOUR WORKSHOP INCLUDES COMPUTE:
- AFTER THE WORKSHOP, ADD DATA DOWNLOAD LINKS, AWS MACHINE IMAGE INSTRUCTIONS, ETC.
- IF IT IS MORE APPROPRIATE, YOU CAN INCLUDE THE DATA DOWNLOAD LINKS IN EACH OF THE MODULES.
-->

# Data and Compute Setup

## Course data downloads
Coming soon!

## Compute setup

### AWS and Unix Intro

#### Connecting and Properly Using a Cloud Computring Cluster at the CBW
*By Jose Hecter Galvez, Zhibin Lu, and Rob Syme*

##### Schedule:

|       |                                Day 1                                |
|-------|:-------------------------------------------------------------------:|
| 10:00 |                    Welcome Introduction (Rachade)                   |
| 10:10 |                 Module 0 : AWS EC2 instance (Zhibin)                |
| 10:40 | Module 1: Logging into AWS (group split into Windows and Mac/Linux) |
| 11:10 |                                Break                                |
| 11:15 |       Module 2: Introduction to the UNIX Command Line (Hector)      |
| 11:35 |                     Module 3: File Manipulation                     |
| 12:05 |                                Break                                |
| 13:05 |         Module 4: Searching and Sorting Through Files (Rob)         |
| 14:00 |                                Break                                |
| 14:05 |                    Module 5: Shell scripts (Rob)                    |
| 15:00 |                                                                     |

##### 1. Logging into AWS

Description of the lab:

This section will show students how to login to AWS and create an instance

<iframe src="https://drive.google.com/file/d/1Vf1uiJPpY8025pJjsWNFvgK-ImqkGmVE/preview" width="640" height="480" allow="autoplay"></iframe>

Once you have confirmed your account as per the email (subject line “You have been invited to join an AWS Educate Classroom”), you can log in here:

[www.awseducate.com](www.awseducate.com)

##### 2. Introduction to the Command Line

Description of the lab:

This section will show students the basics of the command line, with a focus on navigation.

<iframe src="https://drive.google.com/file/d/1gTOzpP_VUjR7vIPidLWABps9jh5mYvA0/preview" width="640" height="480" allow="autoplay"></iframe>

###### Exercise: Exploring the filesystem

1. Connect to your AWS instance
2. Type the `ls` command, what do you see?
  <details>
    <summary>Solution (click here)</summary>
    
    ``` $ ls CourseData R cvmfs_cache workspace ``` The `ls` command lists the contents of a working directory.
  
  </details>

3. After following the tutorial, can you answer what these commands (`cd`, `pwd`) do?
  <details>
    <summary>Solution (click here)</summary>
    
    The `cd` command is used to *change directories*. Without arguments, it will move to the home directory (`~`) The `pwd` command shows the absolute     *path to the working directory*.
  
  </details>

##### 3. File Manipulation

Description of the lab:

This section will show students how to manipulate files, including reading, editing, and renamming text files.

<iframe src="https://drive.google.com/file/d/1gYHurIPaOlmxZMtVXDqjDW8L-jZfFzr6/preview" width="640" height="480" allow="autoplay"></iframe>

Additional material:

Here are two cheat-sheets that can be usedful to have as a reference for common UNIX/Linux commands:

- [FOSSwire.com Unix/Linux Command Reference](https://files.fosswire.com/2007/08/fwunixref.pdf)
- [SUSO.org Unix/Linux Command Syntax and Reference](https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2F6s2q64ticje51.png)

###### Excercise: Reading Text Files

1. What do the commands `cat`, `head`, and `tail` do? What do they have in common?
  <details>
    <summary>Solution (click here)</summary>
    
    All three of these commands ouptut the contents of a text file to *standard out*: - `cat` outputs the *full* contents of the file - `head` outputs     the *first* 10 lines of a file - `tail` outputs the *last* 10 lines of a file
  
  </details>

2. What does the command `less` do? How is it different from `cat`?
  <details>
    <summary>Solution (click here)</summary>
    
    `less` opens a text file for viewing. Unlike `cat`, it will display it in a separate file viewer.
  
  </details>

3. How can you know the number of lines in a file?
  <details>
    <summary>Solution (click here)</summary>
    
    The command `wc -l` will display the number of lines in a file. `wc` (word count) displays the number of words, lines, and bytes in a file. The       `-l` option, limits the output to lines.
  
  </details>
  
###### Excercise: Editing Text Files

1. Write “Hello world” into a file called `helloworld.txt` using `nano`. Save and then exit.
  <details>
    <summary>Solution (click here)</summary>
    
    First, use the `nano` command to open a file called `helloworld.txt` ``` $ nano helloworld.txt ``` Inside the nano editor, write "Hello world" and     then use the `^O` option to write the changes and then `^X` to exit.
  
  </details>

2. Create a subdirectory called `test`. Then, move the `helloworld.txt` file into the directory.
  <details>
    <summary>Solution (click here)</summary>
    
    First, use the command `mkdir` to create this new directory. Then, use `mv` to move `helloworld.txt` into this directory. ``` $ mkdir test $ mv       helloworld.txt test/ ```
  
  </details>
  
3. Create a copy of the `helloworld.txt file` called `helloworld2.txt`, inside the `test` directory.
  <details>
    <summary>Solution (click here)</summary>
    
    First, change the working directory using `cd`, then use the `cp` command to create the copy. ``` $ cd test $ cp helloworld.txt helloworld2.txt       ```
  
  </details>
  
##### 4. Searching and Sorting Files

Description of the lab:

This section will show students how to search for files and in files.

Workshop notes and quiz questions [here.]()

##### 5. Putting it all Together

Description of the lab:

This section will show students how the basic concepts fit together and in the context of bioinformatics.

Workshop notes and quiz questions [here.]()

##### 6. AWS Machine Image (AMI)

Starting the AWS AMI after the workshop is over:

An updated AWS Machine Image (AMI) will be be prepred by Zhibin at the end of this CBW workshop: It will have the same software used in the workshop, but it will not contain any of the data. To get such an image started, you will need to set up your own AWS account with your own credit card, and then, the same as you did in this workshop, look for the CBW AMI, and start that with your own project.

[Launching the AMI](https://bioinformatics-ca.github.io/bioinformatics_for_cancer_genomics_AMI_2015/)
